GET http://localhost:3000

###
GET http://localhost:3000/help

###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "William",
    "password": "sdasds",
    "email": "wildliadm@gmail.com"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "William",
    "password": "sdasds",
    "email": "wildliam@gmail.com"
}

###
GET http://localhost:3000/games

###
POST http://localhost:3000/games/create
Content-Type: application/json

{
    "title": "testsss"
}

### 
GET http://localhost:3000/games/user
Content-Type: application/json

{
    "ids": ["61f230c456413b13efedbd6a", "61f230a856413b13efedbd67"]
}